### ISSUE TITLE
Could not able to run 

### ISSUE THREAD

**Issue by SaddamBInSyed** [cengiz7/MotionControl#1]
@cengiz7 

thanks for your work.

when I run the darknet_video.py file I am getting the below error.

  File "C:/Users/saddam.h.SMARTV/Downloads/MotionControl-master/MotionControl-master/darknet_video.py", line 5, in <module>
    import darknet_dll
  File "C:\Users\saddam.h.SMARTV\Downloads\MotionControl-master\MotionControl-master\darknet_dll.py", line 114, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

my os : win10 64 bit with NO GPU.

also, could you upload the "yolo_cpp_dll_nogpu.dll" ?

please advise.

**Comment by cengiz7** [comment]
You have to have a GPU with cuda and CUDNN supported in order to run Darknet YOLOv3.

**Comment by SaddamBInSyed** [comment]
Thanks for the response.

by the way.,  are you using yolo to detect your hand ? if not how you are detecting the hand,

please advise

**Comment by SaddamBInSyed** [comment]
In addition to the above,

I just want to move my mouse smoothly with hand.
could you please advise any working method.

currently, I am detecting my hand and finding the center of the hand, and using pyautogui I am moving my mouse pointer but due to hand detection noisy output, I could not able to get smoothness over the Ui controls. 

help appreciated.

**Comment by cengiz7** [comment]
1- You can fallow the instructions here for gpuless build [Github Yolo](https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll-and-so-libraries)
2- Yes i am using YOLOv3 for detecting hand signs and movements. I trained my own weight file but i do not upload it here.
3- By my solution in this project, you just need good FPS (over 15fps) with this technique. Moving mouse smoothly is very tricky problem. You need to consider everthing before choosing the right algorithm.
